# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    docker-compose -f docker-compose.yml --project-directory .  -d
    docker-compose run web gem install bundler
    docker-compose run web bundle install
    docker-compose run web bundle exec rake db:create
    docker-compose run web bundle exec rake db:migrate
    docker-compose run web bundle exec rspec
    docker-compose -f docker-compose.yml --project-directory . down