# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    - docker-compose up -d
    - docker-compose run web gem install bundler
    - docker-compose run web bundle install
    - docker-compose run web bundle exec rake db:create
    - docker-compose run web bundle exec rake db:migrate
    - docker-compose run web bundle exec rspec
  displayName: 'Run the specs'
