version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: |
        curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
        chmod +x ~/docker-compose
        sudo mv ~/docker-compose /usr/local/bin/docker-compose
        docker-compose up -d
        docker-compose run web gem install bundler
        docker-compose run web bundle install
        docker-compose run web bundle exec rake db:create
        docker-compose run web bundle exec rake db:migrate
        docker-compose run web bundle exec rspec
