version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: |
        docker-compose up -d
        docker-compose run web gem install bundler
        docker-compose run web bundle install
        docker-compose run web bundle exec rake db:create
        docker-compose run web bundle exec rake db:migrate
        docker-compose run web bundle exec rspec
